#test
SCCL2.Combustion<-SCC[grepl("Combustion",SCC$SCC.Level.Two),]
SCCL3.Combustion<-SCC[grepl("Combustion",SCC$SCC.Level.Three),]
SCCL1.Combustion<-SCC[grepl("Combustion",SCC$SCC.Level.One),]
SCCL4.Combustion<-SCC[grepl("Combustion",SCC$SCC.Level.Four),]
SCCl1.Comb.unq<-as.data.frame(unique(SCCL1.Combustion$SCC.Level.One))
SCCl2.Comb.unq<-as.data.frame(unique(SCCL2.Combustion$SCC.Level.Two))
SCCl3.Comb.unq<-as.data.frame(unique(SCCL3.Combustion$SCC.Level.Three))
SCCl4.Comb.unq<-as.data.frame(unique(SCCL4.Combustion$SCC.Level.Four))
SCCL1.Coal<-SCC[grepl("Coal",SCC$SCC.Level.One),]
SCCL2.Coal<-SCC[grepl("Coal",SCC$SCC.Level.Two),]
SCCL3.Coal<-SCC[grepl("Coal",SCC$SCC.Level.Three),]
SCCL4.Coal<-SCC[grepl("Coal",SCC$SCC.Level.Four),]
SCCl4.Coal.unq<-as.data.frame(unique(SCCL4.Coal$SCC.Level.Four))
SCCl3.Coal.unq<-as.data.frame(unique(SCCL3.Coal$SCC.Level.Three))
SCCl2.Coal.unq<-as.data.frame(unique(SCCL2.Coal$SCC.Level.Two))
SCCl1.Coal.unq<-as.data.frame(unique(SCCL1.Coal$SCC.Level.One))

SCCEIS.Coal<-SCC[grepl("Coal",SCC$EI.Sector),]
SCCEISl.unq<-as.data.frame(unique(SCCEIS.Coal$EI.Sector))
